Life: Ant Class Reference
Ant Class Reference
#include <Ant.h>
Public Member Functions
Ant ()
Ant (int r=0, int c=0)
int getRow ()
int getCol ()
int getBreedCounter ()
int move (Grid *grid)
void moveHelper (Grid *grid, int dir)
void breedHelper (Grid *grid, int dir)
bool breed (Grid *grid)
~Ant ()
Public Member Functions inherited from Organism
Organism ()
Organism (bool b)
bool isPrey ()
void setAmAnt (bool b)
virtual ~Organism ()
Private Attributes
int row = 0
int col = 0
int breedCounter =0
Constructor & Destructor Documentation
Ant() [1/2]
Ant::Ant ()
Ant() [2/2]
Ant::Ant (int r = 0, int c = 0)
References col, and row.
~Ant()
Ant::~Ant ()
Member Function Documentation
breed()
bool Ant::breed (Grid * grid) virtual
Implements Organism.
References breedCounter, breedHelper(), col, empty, Grid::findNeighbours(), Grid::randInt(), and row.
Referenced by move().
breedHelper()
void Ant::breedHelper (Grid * grid, int dir)
References ant, col, Grid::getBoard(), Cell::NewPtr(), row, and Grid::setCellOccupant().
Referenced by breed().
getBreedCounter()
int Ant::getBreedCounter ()
References breedCounter.
getCol()
int Ant::getCol ()
References col.
getRow()
int Ant::getRow ()
References row.
move()
int Ant::move (Grid * grid) virtual
Implements Organism.
References breed(), breedCounter, col, empty, Grid::findNeighbours(), Grid::getBoard(), moveHelper(), Grid::randInt(), row, Grid::setCellOccupant(), and Cell::setPtr().
moveHelper()
void Ant::moveHelper (Grid * grid, int dir)
References ant, col, Grid::getBoard(), Cell::getPtr(), row, Grid::setCellOccupant(), and Cell::setPtr().
Referenced by move().
Field Documentation
breedCounter
int Ant::breedCounter =0 private
Referenced by breed(), getBreedCounter(), and move().
col
int Ant::col = 0 private
Referenced by Ant(), breed(), breedHelper(), getCol(), move(), and moveHelper().
row
int Ant::row = 0 private
Referenced by Ant(), breed(), breedHelper(), getRow(), move(), and moveHelper().
The documentation for this class was generated from the following files:
Ant.h
Ant.cpp