Life: Organism Class Reference
Organism Class Reference abstract
#include <Organism.h>
Public Member Functions
Organism ()
Organism (bool b)
bool isPrey ()
virtual int move (Grid *grid)=0
virtual bool breed (Grid *grid)=0
void setAmAnt (bool b)
virtual ~Organism ()
Constructor & Destructor Documentation
Organism() [1/2]
Organism::Organism ()
Organism() [2/2]
Organism::Organism (bool b)
References amAnt.
~Organism()
Organism::~Organism () virtual
Member Function Documentation
breed()
virtual bool Organism::breed (Grid * grid) pure virtual
Implemented in Doodlebug, and Ant.
isPrey()
bool Organism::isPrey ()
References amAnt.
move()
virtual int Organism::move (Grid * grid) pure virtual
Implemented in Doodlebug, and Ant.
Referenced by Tests2::antsBreedTest(), Tests2::antsDieTest(), Tests2::antsMoveTest(), Tests2::doodleBreedTest(), Tests2::doodleDietest(), Tests2::doodleMoveTest(), and Production::runProduction().
setAmAnt()
void Organism::setAmAnt (bool b)
References amAnt.
The documentation for this class was generated from the following files:
Organism.h
Organism.cpp