Life: Doodlebug Class Reference
Doodlebug Class Reference
#include <Doodlebug.h>
Public Member Functions
Doodlebug ()
Doodlebug (int r=0, int c=0)
int getRow ()
int getCol ()
int getBreedCounter ()
int getDeathCounter ()
int move (Grid *grid)
void moveHelper (Grid *grid, int dir)
void breedHelper (Grid *grid, int dir)
bool breed (Grid *grid)
int eat (Grid *grid, bool *arrAnts)
virtual ~Doodlebug ()
Public Member Functions inherited from Organism
Organism ()
Organism (bool b)
bool isPrey ()
void setAmAnt (bool b)
virtual ~Organism ()
Private Attributes
int row = 0
int col = 0
int breedCounter =0
int deathCount =0
Constructor & Destructor Documentation
Doodlebug() [1/2]
Doodlebug::Doodlebug ()
Doodlebug() [2/2]
Doodlebug::Doodlebug (int r = 0, int c = 0)
References col, and row.
~Doodlebug()
Doodlebug::~Doodlebug () virtual
Member Function Documentation
breed()
bool Doodlebug::breed (Grid * grid) virtual
Implements Organism.
References breedCounter, breedHelper(), col, empty, Grid::findNeighbours(), Grid::randInt(), and row.
Referenced by move().
breedHelper()
void Doodlebug::breedHelper (Grid * grid, int dir)
References col, doodlebug, Grid::getBoard(), Cell::NewPtr(), row, and Grid::setCellOccupant().
Referenced by breed().
eat()
int Doodlebug::eat (Grid * grid, bool * arrAnts)
References breedCounter, col, deathCount, empty, Grid::getBoard(), moveHelper(), Grid::randInt(), row, Grid::setCellOccupant(), and Cell::setPtr().
Referenced by move().
getBreedCounter()
int Doodlebug::getBreedCounter ()
References breedCounter.
getCol()
int Doodlebug::getCol ()
References deathCount.
getDeathCounter()
int Doodlebug::getDeathCounter ()
References deathCount.
getRow()
int Doodlebug::getRow ()
References row.
move()
int Doodlebug::move (Grid * grid) virtual
Implements Organism.
References ant, breed(), breedCounter, col, deathCount, eat(), empty, Grid::findNeighbours(), Grid::getBoard(), moveHelper(), Grid::randInt(), row, Grid::setCellOccupant(), and Cell::setPtr().
moveHelper()
void Doodlebug::moveHelper (Grid * grid, int dir)
References col, doodlebug, empty, Grid::getBoard(), Cell::getPtr(), row, Grid::setCellOccupant(), and Cell::setPtr().
Referenced by eat(), and move().
Field Documentation
breedCounter
int Doodlebug::breedCounter =0 private
Referenced by breed(), eat(), getBreedCounter(), and move().
col
int Doodlebug::col = 0 private
Referenced by breed(), breedHelper(), Doodlebug(), eat(), move(), and moveHelper().
deathCount
int Doodlebug::deathCount =0 private
Referenced by eat(), getCol(), getDeathCounter(), and move().
row
int Doodlebug::row = 0 private
Referenced by breed(), breedHelper(), Doodlebug(), eat(), getRow(), move(), and moveHelper().
The documentation for this class was generated from the following files:
Doodlebug.h
Doodlebug.cpp