Life: Grid Class Reference
Grid Class Reference
#include <Grid.h>
Public Member Functions
Grid ()
Grid (int nSquaresOnASide)
Cell ** getBoard ()
bool setCellOccupant (int r, int c, occupationStatus g)
occupationStatus getCellOccupant (int r, int c)
bool * findNeighbours (int r, int c, occupationStatus g)
int randInt (int n)
void printGrid ()
virtual ~Grid ()
Data Fields
Cell ** board
int size =0
Constructor & Destructor Documentation
Grid() [1/2]
Grid::Grid ()
References board.
Grid() [2/2]
Grid::Grid (int nSquaresOnASide)
References board, and size.
~Grid()
Grid::~Grid () virtual
References board, size, and Cell::~Cell().
Referenced by Tests2::gridTest().
Member Function Documentation
findNeighbours()
bool * Grid::findNeighbours (int r, int c, occupationStatus g)
References board, and size.
Referenced by Ant::breed(), Doodlebug::breed(), Ant::move(), and Doodlebug::move().
getBoard()
Cell ** Grid::getBoard ()
References board.
Referenced by Tests2::antsBreedTest(), Tests2::antsDieTest(), Tests2::antsMoveTest(), Ant::breedHelper(), Doodlebug::breedHelper(), Tests2::doodleBreedTest(), Tests2::doodleDietest(), Tests2::doodleMoveTest(), Doodlebug::eat(), Ant::move(), Doodlebug::move(), Ant::moveHelper(), Doodlebug::moveHelper(), and Production::runProduction().
getCellOccupant()
occupationStatus Grid::getCellOccupant (int r, int c)
References board, and Cell::getOccupant().
Referenced by Tests2::gridTest(), Tests2::makeAntsTest(), printGrid(), and Production::runProduction().
printGrid()
void Grid::printGrid ()
References ant, doodlebug, empty, getCellOccupant(), and size.
Referenced by Tests2::antsDieTest(), Tests2::doodleBreedTest(), Tests2::doodleDietest(), and Production::runProduction().
randInt()
int Grid::randInt (int n)
Referenced by Ant::breed(), Doodlebug::breed(), Doodlebug::eat(), Ant::move(), Doodlebug::move(), and Production::runProduction().
setCellOccupant()
bool Grid::setCellOccupant (int r, int c, occupationStatus g)
References board, and Cell::setOccupant().
Referenced by Tests2::antsBreedTest(), Tests2::antsDieTest(), Tests2::antsMoveTest(), Ant::breedHelper(), Doodlebug::breedHelper(), Tests2::doodleBreedTest(), Tests2::doodleDietest(), Tests2::doodleMoveTest(), Doodlebug::eat(), Tests2::gridTest(), Tests2::makeAntsTest(), Ant::move(), Doodlebug::move(), Ant::moveHelper(), Doodlebug::moveHelper(), and Production::runProduction().
Field Documentation
board
Cell** Grid::board
Referenced by findNeighbours(), getBoard(), getCellOccupant(), Grid(), setCellOccupant(), and ~Grid().
size
int Grid::size =0
Referenced by findNeighbours(), Grid(), printGrid(), and ~Grid().
The documentation for this class was generated from the following files:
Grid.h
Grid.cpp