Life: Cell Class Reference
Cell Class Reference
#include <Cell.h>
Public Member Functions
Cell ()
bool setOccupant (occupationStatus g)
void NewPtr (int r, int c, occupationStatus g)
Organism * getPtr ()
void setPtr (Organism *newPtr)
occupationStatus getOccupant ()
virtual ~Cell ()
Data Fields
occupationStatus guest
Organism * ptr
Constructor & Destructor Documentation
Cell()
Cell::Cell ()
References empty, guest, and ptr.
~Cell()
Cell::~Cell () virtual
Referenced by Grid::~Grid().
Member Function Documentation
getOccupant()
occupationStatus Cell::getOccupant ()
References guest.
Referenced by Grid::getCellOccupant().
getPtr()
Organism * Cell::getPtr ()
References ptr.
Referenced by Tests2::antsBreedTest(), Tests2::antsDieTest(), Tests2::antsMoveTest(), Tests2::doodleBreedTest(), Tests2::doodleDietest(), Tests2::doodleMoveTest(), Ant::moveHelper(), Doodlebug::moveHelper(), and Production::runProduction().
NewPtr()
void Cell::NewPtr (int r, int c, occupationStatus g)
References ant, doodlebug, empty, and ptr.
Referenced by Tests2::antsBreedTest(), Tests2::antsDieTest(), Tests2::antsMoveTest(), Ant::breedHelper(), Doodlebug::breedHelper(), Tests2::doodleBreedTest(), Tests2::doodleDietest(), Tests2::doodleMoveTest(), and Production::runProduction().
setOccupant()
bool Cell::setOccupant (occupationStatus g)
References empty, and guest.
Referenced by Grid::setCellOccupant().
setPtr()
void Cell::setPtr (Organism * newPtr)
References ptr.
Referenced by Doodlebug::eat(), Ant::move(), Doodlebug::move(), Ant::moveHelper(), and Doodlebug::moveHelper().
Field Documentation
guest
occupationStatus Cell::guest
Referenced by Cell(), getOccupant(), and setOccupant().
ptr
Organism* Cell::ptr
Referenced by Cell(), getPtr(), NewPtr(), and setPtr().
The documentation for this class was generated from the following files:
Cell.h
Cell.cpp